[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bleach>=6.2.0",
    "python-socketio>=5.13.0",
    "validators>=0.35.0",
]
